version: '3.6'
services:
    landing:
        build:
            context: './'
            dockerfile: Dockerfile
        container_name: docker-nextjs
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
